### ISSUE TITLE
unable to generate models from mssql db on Azure

### ISSUE THREAD

**Issue by fideliselite** [sequelize/sequelize-auto#356]
When I run sequelize-auto from the command line I get the following error:
`     message:
      'Server requires encryption, set \'encrypt\' config option to true.',
     code: 'EENCRYPT' } }`

I set encrypt = true for sequelize in order to get that working but i'm not sure where/how to set encrypt to truue for sequelize auto. Anyone know how to do this?

**Comment by 4umfreak** [comment]
Looks like there's a -c option in sequelize-auto that will allow you to pass the name of a sequelize config JSON file...  I haven't tried it but it might work.

**Comment by steveschmitt** [comment]
Any luck with this?  Please try `sequelize-auto@0.5.0` which works with the latest `tedious` library.

**Comment by steveschmitt** [comment]
For specific options, you can use the [Programmatic API](https://github.com/sequelize/sequelize-auto/blob/master/README.md#programmatic-api) as shown in the [README](https://github.com/sequelize/sequelize-auto/blob/master/README.md#programmatic-api).

You can include the sequelize `encrypt` option with the other options:
```js
const auto = new SequelizeAuto('database', 'user', 'pass', {
    host: 'my.azure.db.site.net',
    dialect: 'mssql',
    port: '1433',
    dialectOptions: {
        encrypt: true
    }
})
```

Or, you can create the Sequelize instance and pass that to SequelizeAuto (instead of the database name) as the first parameter in the constructor:
```js
const SequelizeAuto = require('sequelize-auto');
const Sequelize = require('sequelize');

const sequelize = new Sequelize('database', 'username', 'password', {
    host: 'localhost',
    dialect: 'mssql',
    dialectOptions: {
        encrypt: true
    }
});
const autoOptions = { caseFile: 'l', caseModel: 'p', caseProp: 'c' };

const auto = new SequelizeAuto(sequelize, null, null, autoOptions);
auto.run();
```
