### ISSUE TITLE
PK with autoincrement is set to false in "allowNull"

### ISSUE THREAD

**Issue by Nosthertus** [sequelize/sequelize-auto#40]
Sequelize doesn't let me create new records without setting the `id` in this case, which is an `PK` and `autoIncrement` column in database, this is by logic setting `null` to `false`, so sequelize must detect if `autoIncrement` is set so it could ignore this whenever i create a new record

**Comment by durango** [comment]
@Nosthertus not sure if the latest version `0.2.6` fixes this issue with generating the primary key (it's been a while since I've worked on the actual sequelize lib). We now set the `autoIncrement` column correctly, but I'm not 100% sure if this surpasses the `allowNull` option.

Let me know if you run into any issues and I'll be more than happy to look into the situation.
