### ISSUE TITLE
When reverse engineering the db to models using the sequelize-auto

### ISSUE THREAD

**Issue by tmli3b3rm4n** [sequelize/sequelize-auto#96]
`sequelize-auto -h 127.0.0.1 -d database -u user -p 3306 -o outputDirectory` It doesn't add string lengths to the `dataTypes.String()`.

**Comment by DaveRicho** [comment]
Yes, I am having almost the same issue (using mssql dialect). I think part of the problem is that the _attr variable in lines 238 (see below) does not ever contain maximum column length data. For example, _attr will be 'varchar' for a column that is varchar(20).

The second line of this snippet never contains a positive match because _attr never contains the brackets and numbers
```
else if (_attr.match(/^string|varchar|varying|nvarchar/)) { //this will match to 'varchar'
              var length = _attr.match(/\(\d+\)/); //sadly, this is always be null as _attr will not have the (20) part
```

**Comment by durango** [comment]
varchar should now define lengths, please let me know if you need another data type to support lengths (please provide a schema example as well).
